# Generated by Django 5.1.1 on 2024-09-24 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='gender',
            field=models.CharField(choices=[('male', '男性'), ('female', '女性'), ('other', 'その他')], max_length=10),
        ),
    ]
