# Generated by Django 5.1.1 on 2024-09-24 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_userdata_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='gender',
            field=models.IntegerField(choices=[(0, '男性'), (1, '女性'), (2, 'その他')], default='0'),
        ),
    ]
