# Generated by Django 5.1.1 on 2024-09-24 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_userdata_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='gender',
            field=models.IntegerField(choices=[(0, '男性'), (1, '女性'), (2, 'その他')], default=0),
        ),
    ]
